/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type FuelType = { 'petrol' : null } |
  { 'electric' : null };
export interface TwoWheeler {
  'engineNumber' : string,
  'model' : string,
  'vehicleType' : VehicleType,
  'ownerName' : string,
  'color' : string,
  'manufacturingYear' : bigint,
  'registrationNumber' : string,
  'odometer' : bigint,
  'vehicleCondition' : VehicleCondition,
  'fuelType' : FuelType,
  'notes' : string,
  'chassisNumber' : string,
  'contactNumber' : string,
  'brand' : string,
  'engineOrBatteryCapacity' : bigint,
  'variant' : [] | [string],
}
export interface VehicleCondition {
  'headLight' : [] | [string],
  'tailLamp' : [] | [string],
  'switches' : [] | [string],
  'bodyTypeScooter' : [] | [string],
  'silencerCover' : [] | [string],
  'forkBend' : [] | [string],
  'horn' : [] | [string],
  'remoteKeyWorking' : [] | [string],
  'keys' : [] | [string],
  'fuelTankCondition' : [] | [string],
  'engineCondition' : [] | [string],
  'silencer' : [] | [string],
  'acceleratorCondition' : [] | [string],
  'discBrakesRear' : [] | [string],
  'rearShockAbsorber' : [] | [string],
  'rearLHIndicator' : [] | [string],
  'rearRHIndicator' : [] | [string],
  'frontLHIndicator' : [] | [string],
  'frontRHIndicator' : [] | [string],
  'cubicCapacityCC' : [] | [string],
  'brakesCondition' : [] | [string],
  'rearBrakeLever' : [] | [string],
  'discBrakesFront' : [] | [string],
  'speedometerTachometer' : [] | [string],
  'tyre2Life' : [] | [string],
  'tailLight' : [] | [string],
  'rearShockAbsorberType' : [] | [string],
  'fuelTank' : [] | [string],
  'mudGuardFront' : [] | [string],
  'frontShockAbsorber' : [] | [string],
  'gearShiftLever' : [] | [string],
  'mainStand' : [] | [string],
  'indicators' : [] | [string],
  'frontScoop' : [] | [string],
  'sideCovers' : [] | [string],
  'handleBar' : [] | [string],
  'paintCondition' : [] | [string],
  'selfStart' : [] | [string],
  'mudGuardRear' : [] | [string],
  'battery' : [] | [string],
  'alloyOrWheelRim' : [] | [string],
  'speedometerPanel' : [] | [string],
  'engineFunction' : [] | [string],
  'fuelGauge' : [] | [string],
  'radiator' : [] | [string],
  'tyre1Life' : [] | [string],
  'ignition' : [] | [string],
  'sideStand' : [] | [string],
  'clutchCondition' : [] | [string],
}
export type VehicleType = { 'motorcycle' : null } |
  { 'bike' : null } |
  { 'scooter' : null };
export interface _SERVICE {
  'addTwoWheeler' : ActorMethod<[TwoWheeler], undefined>,
  'getAllTwoWheelersByYear' : ActorMethod<[], Array<TwoWheeler>>,
  'getTwoWheeler' : ActorMethod<[string], TwoWheeler>,
  'removeTwoWheeler' : ActorMethod<[string], undefined>,
  'updateTwoWheeler' : ActorMethod<[string, TwoWheeler], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];