/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VehicleType = IDL.Variant({
  'motorcycle' : IDL.Null,
  'bike' : IDL.Null,
  'scooter' : IDL.Null,
});
export const VehicleCondition = IDL.Record({
  'headLight' : IDL.Opt(IDL.Text),
  'tailLamp' : IDL.Opt(IDL.Text),
  'switches' : IDL.Opt(IDL.Text),
  'bodyTypeScooter' : IDL.Opt(IDL.Text),
  'silencerCover' : IDL.Opt(IDL.Text),
  'forkBend' : IDL.Opt(IDL.Text),
  'horn' : IDL.Opt(IDL.Text),
  'remoteKeyWorking' : IDL.Opt(IDL.Text),
  'keys' : IDL.Opt(IDL.Text),
  'fuelTankCondition' : IDL.Opt(IDL.Text),
  'engineCondition' : IDL.Opt(IDL.Text),
  'silencer' : IDL.Opt(IDL.Text),
  'acceleratorCondition' : IDL.Opt(IDL.Text),
  'discBrakesRear' : IDL.Opt(IDL.Text),
  'rearShockAbsorber' : IDL.Opt(IDL.Text),
  'rearLHIndicator' : IDL.Opt(IDL.Text),
  'rearRHIndicator' : IDL.Opt(IDL.Text),
  'frontLHIndicator' : IDL.Opt(IDL.Text),
  'frontRHIndicator' : IDL.Opt(IDL.Text),
  'cubicCapacityCC' : IDL.Opt(IDL.Text),
  'brakesCondition' : IDL.Opt(IDL.Text),
  'rearBrakeLever' : IDL.Opt(IDL.Text),
  'discBrakesFront' : IDL.Opt(IDL.Text),
  'speedometerTachometer' : IDL.Opt(IDL.Text),
  'tyre2Life' : IDL.Opt(IDL.Text),
  'tailLight' : IDL.Opt(IDL.Text),
  'rearShockAbsorberType' : IDL.Opt(IDL.Text),
  'fuelTank' : IDL.Opt(IDL.Text),
  'mudGuardFront' : IDL.Opt(IDL.Text),
  'frontShockAbsorber' : IDL.Opt(IDL.Text),
  'gearShiftLever' : IDL.Opt(IDL.Text),
  'mainStand' : IDL.Opt(IDL.Text),
  'indicators' : IDL.Opt(IDL.Text),
  'frontScoop' : IDL.Opt(IDL.Text),
  'sideCovers' : IDL.Opt(IDL.Text),
  'handleBar' : IDL.Opt(IDL.Text),
  'paintCondition' : IDL.Opt(IDL.Text),
  'selfStart' : IDL.Opt(IDL.Text),
  'mudGuardRear' : IDL.Opt(IDL.Text),
  'battery' : IDL.Opt(IDL.Text),
  'alloyOrWheelRim' : IDL.Opt(IDL.Text),
  'speedometerPanel' : IDL.Opt(IDL.Text),
  'engineFunction' : IDL.Opt(IDL.Text),
  'fuelGauge' : IDL.Opt(IDL.Text),
  'radiator' : IDL.Opt(IDL.Text),
  'tyre1Life' : IDL.Opt(IDL.Text),
  'ignition' : IDL.Opt(IDL.Text),
  'sideStand' : IDL.Opt(IDL.Text),
  'clutchCondition' : IDL.Opt(IDL.Text),
});
export const FuelType = IDL.Variant({
  'petrol' : IDL.Null,
  'electric' : IDL.Null,
});
export const TwoWheeler = IDL.Record({
  'engineNumber' : IDL.Text,
  'model' : IDL.Text,
  'vehicleType' : VehicleType,
  'ownerName' : IDL.Text,
  'color' : IDL.Text,
  'manufacturingYear' : IDL.Nat,
  'registrationNumber' : IDL.Text,
  'odometer' : IDL.Nat,
  'vehicleCondition' : VehicleCondition,
  'fuelType' : FuelType,
  'notes' : IDL.Text,
  'chassisNumber' : IDL.Text,
  'contactNumber' : IDL.Text,
  'brand' : IDL.Text,
  'engineOrBatteryCapacity' : IDL.Nat,
  'variant' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addTwoWheeler' : IDL.Func([TwoWheeler], [], []),
  'getAllTwoWheelersByYear' : IDL.Func([], [IDL.Vec(TwoWheeler)], ['query']),
  'getTwoWheeler' : IDL.Func([IDL.Text], [TwoWheeler], ['query']),
  'removeTwoWheeler' : IDL.Func([IDL.Text], [], []),
  'updateTwoWheeler' : IDL.Func([IDL.Text, TwoWheeler], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VehicleType = IDL.Variant({
    'motorcycle' : IDL.Null,
    'bike' : IDL.Null,
    'scooter' : IDL.Null,
  });
  const VehicleCondition = IDL.Record({
    'headLight' : IDL.Opt(IDL.Text),
    'tailLamp' : IDL.Opt(IDL.Text),
    'switches' : IDL.Opt(IDL.Text),
    'bodyTypeScooter' : IDL.Opt(IDL.Text),
    'silencerCover' : IDL.Opt(IDL.Text),
    'forkBend' : IDL.Opt(IDL.Text),
    'horn' : IDL.Opt(IDL.Text),
    'remoteKeyWorking' : IDL.Opt(IDL.Text),
    'keys' : IDL.Opt(IDL.Text),
    'fuelTankCondition' : IDL.Opt(IDL.Text),
    'engineCondition' : IDL.Opt(IDL.Text),
    'silencer' : IDL.Opt(IDL.Text),
    'acceleratorCondition' : IDL.Opt(IDL.Text),
    'discBrakesRear' : IDL.Opt(IDL.Text),
    'rearShockAbsorber' : IDL.Opt(IDL.Text),
    'rearLHIndicator' : IDL.Opt(IDL.Text),
    'rearRHIndicator' : IDL.Opt(IDL.Text),
    'frontLHIndicator' : IDL.Opt(IDL.Text),
    'frontRHIndicator' : IDL.Opt(IDL.Text),
    'cubicCapacityCC' : IDL.Opt(IDL.Text),
    'brakesCondition' : IDL.Opt(IDL.Text),
    'rearBrakeLever' : IDL.Opt(IDL.Text),
    'discBrakesFront' : IDL.Opt(IDL.Text),
    'speedometerTachometer' : IDL.Opt(IDL.Text),
    'tyre2Life' : IDL.Opt(IDL.Text),
    'tailLight' : IDL.Opt(IDL.Text),
    'rearShockAbsorberType' : IDL.Opt(IDL.Text),
    'fuelTank' : IDL.Opt(IDL.Text),
    'mudGuardFront' : IDL.Opt(IDL.Text),
    'frontShockAbsorber' : IDL.Opt(IDL.Text),
    'gearShiftLever' : IDL.Opt(IDL.Text),
    'mainStand' : IDL.Opt(IDL.Text),
    'indicators' : IDL.Opt(IDL.Text),
    'frontScoop' : IDL.Opt(IDL.Text),
    'sideCovers' : IDL.Opt(IDL.Text),
    'handleBar' : IDL.Opt(IDL.Text),
    'paintCondition' : IDL.Opt(IDL.Text),
    'selfStart' : IDL.Opt(IDL.Text),
    'mudGuardRear' : IDL.Opt(IDL.Text),
    'battery' : IDL.Opt(IDL.Text),
    'alloyOrWheelRim' : IDL.Opt(IDL.Text),
    'speedometerPanel' : IDL.Opt(IDL.Text),
    'engineFunction' : IDL.Opt(IDL.Text),
    'fuelGauge' : IDL.Opt(IDL.Text),
    'radiator' : IDL.Opt(IDL.Text),
    'tyre1Life' : IDL.Opt(IDL.Text),
    'ignition' : IDL.Opt(IDL.Text),
    'sideStand' : IDL.Opt(IDL.Text),
    'clutchCondition' : IDL.Opt(IDL.Text),
  });
  const FuelType = IDL.Variant({ 'petrol' : IDL.Null, 'electric' : IDL.Null });
  const TwoWheeler = IDL.Record({
    'engineNumber' : IDL.Text,
    'model' : IDL.Text,
    'vehicleType' : VehicleType,
    'ownerName' : IDL.Text,
    'color' : IDL.Text,
    'manufacturingYear' : IDL.Nat,
    'registrationNumber' : IDL.Text,
    'odometer' : IDL.Nat,
    'vehicleCondition' : VehicleCondition,
    'fuelType' : FuelType,
    'notes' : IDL.Text,
    'chassisNumber' : IDL.Text,
    'contactNumber' : IDL.Text,
    'brand' : IDL.Text,
    'engineOrBatteryCapacity' : IDL.Nat,
    'variant' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addTwoWheeler' : IDL.Func([TwoWheeler], [], []),
    'getAllTwoWheelersByYear' : IDL.Func([], [IDL.Vec(TwoWheeler)], ['query']),
    'getTwoWheeler' : IDL.Func([IDL.Text], [TwoWheeler], ['query']),
    'removeTwoWheeler' : IDL.Func([IDL.Text], [], []),
    'updateTwoWheeler' : IDL.Func([IDL.Text, TwoWheeler], [], []),
  });
};

export const init = ({ IDL }) => { return []; };