/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VehicleCondition {
    headLight?: string;
    tailLamp?: string;
    switches?: string;
    bodyTypeScooter?: string;
    silencerCover?: string;
    forkBend?: string;
    horn?: string;
    remoteKeyWorking?: string;
    keys?: string;
    fuelTankCondition?: string;
    engineCondition?: string;
    silencer?: string;
    acceleratorCondition?: string;
    discBrakesRear?: string;
    rearShockAbsorber?: string;
    rearLHIndicator?: string;
    rearRHIndicator?: string;
    frontLHIndicator?: string;
    frontRHIndicator?: string;
    cubicCapacityCC?: string;
    brakesCondition?: string;
    rearBrakeLever?: string;
    discBrakesFront?: string;
    speedometerTachometer?: string;
    tyre2Life?: string;
    tailLight?: string;
    rearShockAbsorberType?: string;
    fuelTank?: string;
    mudGuardFront?: string;
    frontShockAbsorber?: string;
    gearShiftLever?: string;
    mainStand?: string;
    indicators?: string;
    frontScoop?: string;
    sideCovers?: string;
    handleBar?: string;
    paintCondition?: string;
    selfStart?: string;
    mudGuardRear?: string;
    battery?: string;
    alloyOrWheelRim?: string;
    speedometerPanel?: string;
    engineFunction?: string;
    fuelGauge?: string;
    radiator?: string;
    tyre1Life?: string;
    ignition?: string;
    sideStand?: string;
    clutchCondition?: string;
}
export interface TwoWheeler {
    engineNumber: string;
    model: string;
    vehicleType: VehicleType;
    ownerName: string;
    color: string;
    manufacturingYear: bigint;
    registrationNumber: string;
    odometer: bigint;
    vehicleCondition: VehicleCondition;
    fuelType: FuelType;
    notes: string;
    chassisNumber: string;
    contactNumber: string;
    brand: string;
    engineOrBatteryCapacity: bigint;
    variant?: string;
}
export enum FuelType {
    petrol = "petrol",
    electric = "electric"
}
export enum VehicleType {
    motorcycle = "motorcycle",
    bike = "bike",
    scooter = "scooter"
}
export interface backendInterface {
    addTwoWheeler(record: TwoWheeler): Promise<void>;
    getAllTwoWheelersByYear(): Promise<Array<TwoWheeler>>;
    getTwoWheeler(registrationNumber: string): Promise<TwoWheeler>;
    removeTwoWheeler(registrationNumber: string): Promise<void>;
    updateTwoWheeler(registrationNumber: string, updatedRecord: TwoWheeler): Promise<void>;
}
import type { FuelType as _FuelType, TwoWheeler as _TwoWheeler, VehicleCondition as _VehicleCondition, VehicleType as _VehicleType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTwoWheeler(arg0: TwoWheeler): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTwoWheeler(to_candid_TwoWheeler_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTwoWheeler(to_candid_TwoWheeler_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllTwoWheelersByYear(): Promise<Array<TwoWheeler>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTwoWheelersByYear();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTwoWheelersByYear();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTwoWheeler(arg0: string): Promise<TwoWheeler> {
        if (this.processError) {
            try {
                const result = await this.actor.getTwoWheeler(arg0);
                return from_candid_TwoWheeler_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTwoWheeler(arg0);
            return from_candid_TwoWheeler_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeTwoWheeler(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTwoWheeler(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTwoWheeler(arg0);
            return result;
        }
    }
    async updateTwoWheeler(arg0: string, arg1: TwoWheeler): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTwoWheeler(arg0, to_candid_TwoWheeler_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTwoWheeler(arg0, to_candid_TwoWheeler_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_FuelType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FuelType): FuelType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TwoWheeler_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TwoWheeler): TwoWheeler {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleCondition_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleCondition): VehicleCondition {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    engineNumber: string;
    model: string;
    vehicleType: _VehicleType;
    ownerName: string;
    color: string;
    manufacturingYear: bigint;
    registrationNumber: string;
    odometer: bigint;
    vehicleCondition: _VehicleCondition;
    fuelType: _FuelType;
    notes: string;
    chassisNumber: string;
    contactNumber: string;
    brand: string;
    engineOrBatteryCapacity: bigint;
    variant: [] | [string];
}): {
    engineNumber: string;
    model: string;
    vehicleType: VehicleType;
    ownerName: string;
    color: string;
    manufacturingYear: bigint;
    registrationNumber: string;
    odometer: bigint;
    vehicleCondition: VehicleCondition;
    fuelType: FuelType;
    notes: string;
    chassisNumber: string;
    contactNumber: string;
    brand: string;
    engineOrBatteryCapacity: bigint;
    variant?: string;
} {
    return {
        engineNumber: value.engineNumber,
        model: value.model,
        vehicleType: from_candid_VehicleType_n12(_uploadFile, _downloadFile, value.vehicleType),
        ownerName: value.ownerName,
        color: value.color,
        manufacturingYear: value.manufacturingYear,
        registrationNumber: value.registrationNumber,
        odometer: value.odometer,
        vehicleCondition: from_candid_VehicleCondition_n14(_uploadFile, _downloadFile, value.vehicleCondition),
        fuelType: from_candid_FuelType_n17(_uploadFile, _downloadFile, value.fuelType),
        notes: value.notes,
        chassisNumber: value.chassisNumber,
        contactNumber: value.contactNumber,
        brand: value.brand,
        engineOrBatteryCapacity: value.engineOrBatteryCapacity,
        variant: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.variant))
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    headLight: [] | [string];
    tailLamp: [] | [string];
    switches: [] | [string];
    bodyTypeScooter: [] | [string];
    silencerCover: [] | [string];
    forkBend: [] | [string];
    horn: [] | [string];
    remoteKeyWorking: [] | [string];
    keys: [] | [string];
    fuelTankCondition: [] | [string];
    engineCondition: [] | [string];
    silencer: [] | [string];
    acceleratorCondition: [] | [string];
    discBrakesRear: [] | [string];
    rearShockAbsorber: [] | [string];
    rearLHIndicator: [] | [string];
    rearRHIndicator: [] | [string];
    frontLHIndicator: [] | [string];
    frontRHIndicator: [] | [string];
    cubicCapacityCC: [] | [string];
    brakesCondition: [] | [string];
    rearBrakeLever: [] | [string];
    discBrakesFront: [] | [string];
    speedometerTachometer: [] | [string];
    tyre2Life: [] | [string];
    tailLight: [] | [string];
    rearShockAbsorberType: [] | [string];
    fuelTank: [] | [string];
    mudGuardFront: [] | [string];
    frontShockAbsorber: [] | [string];
    gearShiftLever: [] | [string];
    mainStand: [] | [string];
    indicators: [] | [string];
    frontScoop: [] | [string];
    sideCovers: [] | [string];
    handleBar: [] | [string];
    paintCondition: [] | [string];
    selfStart: [] | [string];
    mudGuardRear: [] | [string];
    battery: [] | [string];
    alloyOrWheelRim: [] | [string];
    speedometerPanel: [] | [string];
    engineFunction: [] | [string];
    fuelGauge: [] | [string];
    radiator: [] | [string];
    tyre1Life: [] | [string];
    ignition: [] | [string];
    sideStand: [] | [string];
    clutchCondition: [] | [string];
}): {
    headLight?: string;
    tailLamp?: string;
    switches?: string;
    bodyTypeScooter?: string;
    silencerCover?: string;
    forkBend?: string;
    horn?: string;
    remoteKeyWorking?: string;
    keys?: string;
    fuelTankCondition?: string;
    engineCondition?: string;
    silencer?: string;
    acceleratorCondition?: string;
    discBrakesRear?: string;
    rearShockAbsorber?: string;
    rearLHIndicator?: string;
    rearRHIndicator?: string;
    frontLHIndicator?: string;
    frontRHIndicator?: string;
    cubicCapacityCC?: string;
    brakesCondition?: string;
    rearBrakeLever?: string;
    discBrakesFront?: string;
    speedometerTachometer?: string;
    tyre2Life?: string;
    tailLight?: string;
    rearShockAbsorberType?: string;
    fuelTank?: string;
    mudGuardFront?: string;
    frontShockAbsorber?: string;
    gearShiftLever?: string;
    mainStand?: string;
    indicators?: string;
    frontScoop?: string;
    sideCovers?: string;
    handleBar?: string;
    paintCondition?: string;
    selfStart?: string;
    mudGuardRear?: string;
    battery?: string;
    alloyOrWheelRim?: string;
    speedometerPanel?: string;
    engineFunction?: string;
    fuelGauge?: string;
    radiator?: string;
    tyre1Life?: string;
    ignition?: string;
    sideStand?: string;
    clutchCondition?: string;
} {
    return {
        headLight: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.headLight)),
        tailLamp: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.tailLamp)),
        switches: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.switches)),
        bodyTypeScooter: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.bodyTypeScooter)),
        silencerCover: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.silencerCover)),
        forkBend: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.forkBend)),
        horn: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.horn)),
        remoteKeyWorking: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.remoteKeyWorking)),
        keys: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.keys)),
        fuelTankCondition: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.fuelTankCondition)),
        engineCondition: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.engineCondition)),
        silencer: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.silencer)),
        acceleratorCondition: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.acceleratorCondition)),
        discBrakesRear: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.discBrakesRear)),
        rearShockAbsorber: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.rearShockAbsorber)),
        rearLHIndicator: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.rearLHIndicator)),
        rearRHIndicator: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.rearRHIndicator)),
        frontLHIndicator: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.frontLHIndicator)),
        frontRHIndicator: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.frontRHIndicator)),
        cubicCapacityCC: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.cubicCapacityCC)),
        brakesCondition: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.brakesCondition)),
        rearBrakeLever: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.rearBrakeLever)),
        discBrakesFront: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.discBrakesFront)),
        speedometerTachometer: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.speedometerTachometer)),
        tyre2Life: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.tyre2Life)),
        tailLight: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.tailLight)),
        rearShockAbsorberType: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.rearShockAbsorberType)),
        fuelTank: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.fuelTank)),
        mudGuardFront: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.mudGuardFront)),
        frontShockAbsorber: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.frontShockAbsorber)),
        gearShiftLever: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.gearShiftLever)),
        mainStand: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.mainStand)),
        indicators: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.indicators)),
        frontScoop: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.frontScoop)),
        sideCovers: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.sideCovers)),
        handleBar: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.handleBar)),
        paintCondition: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.paintCondition)),
        selfStart: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.selfStart)),
        mudGuardRear: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.mudGuardRear)),
        battery: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.battery)),
        alloyOrWheelRim: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.alloyOrWheelRim)),
        speedometerPanel: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.speedometerPanel)),
        engineFunction: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.engineFunction)),
        fuelGauge: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.fuelGauge)),
        radiator: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.radiator)),
        tyre1Life: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.tyre1Life)),
        ignition: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.ignition)),
        sideStand: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.sideStand)),
        clutchCondition: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.clutchCondition))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    motorcycle: null;
} | {
    bike: null;
} | {
    scooter: null;
}): VehicleType {
    return "motorcycle" in value ? VehicleType.motorcycle : "bike" in value ? VehicleType.bike : "scooter" in value ? VehicleType.scooter : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    petrol: null;
} | {
    electric: null;
}): FuelType {
    return "petrol" in value ? FuelType.petrol : "electric" in value ? FuelType.electric : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TwoWheeler>): Array<TwoWheeler> {
    return value.map((x)=>from_candid_TwoWheeler_n10(_uploadFile, _downloadFile, x));
}
function to_candid_FuelType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FuelType): _FuelType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_TwoWheeler_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TwoWheeler): _TwoWheeler {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleCondition_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleCondition): _VehicleCondition {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    engineNumber: string;
    model: string;
    vehicleType: VehicleType;
    ownerName: string;
    color: string;
    manufacturingYear: bigint;
    registrationNumber: string;
    odometer: bigint;
    vehicleCondition: VehicleCondition;
    fuelType: FuelType;
    notes: string;
    chassisNumber: string;
    contactNumber: string;
    brand: string;
    engineOrBatteryCapacity: bigint;
    variant?: string;
}): {
    engineNumber: string;
    model: string;
    vehicleType: _VehicleType;
    ownerName: string;
    color: string;
    manufacturingYear: bigint;
    registrationNumber: string;
    odometer: bigint;
    vehicleCondition: _VehicleCondition;
    fuelType: _FuelType;
    notes: string;
    chassisNumber: string;
    contactNumber: string;
    brand: string;
    engineOrBatteryCapacity: bigint;
    variant: [] | [string];
} {
    return {
        engineNumber: value.engineNumber,
        model: value.model,
        vehicleType: to_candid_VehicleType_n3(_uploadFile, _downloadFile, value.vehicleType),
        ownerName: value.ownerName,
        color: value.color,
        manufacturingYear: value.manufacturingYear,
        registrationNumber: value.registrationNumber,
        odometer: value.odometer,
        vehicleCondition: to_candid_VehicleCondition_n5(_uploadFile, _downloadFile, value.vehicleCondition),
        fuelType: to_candid_FuelType_n7(_uploadFile, _downloadFile, value.fuelType),
        notes: value.notes,
        chassisNumber: value.chassisNumber,
        contactNumber: value.contactNumber,
        brand: value.brand,
        engineOrBatteryCapacity: value.engineOrBatteryCapacity,
        variant: value.variant ? candid_some(value.variant) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    headLight?: string;
    tailLamp?: string;
    switches?: string;
    bodyTypeScooter?: string;
    silencerCover?: string;
    forkBend?: string;
    horn?: string;
    remoteKeyWorking?: string;
    keys?: string;
    fuelTankCondition?: string;
    engineCondition?: string;
    silencer?: string;
    acceleratorCondition?: string;
    discBrakesRear?: string;
    rearShockAbsorber?: string;
    rearLHIndicator?: string;
    rearRHIndicator?: string;
    frontLHIndicator?: string;
    frontRHIndicator?: string;
    cubicCapacityCC?: string;
    brakesCondition?: string;
    rearBrakeLever?: string;
    discBrakesFront?: string;
    speedometerTachometer?: string;
    tyre2Life?: string;
    tailLight?: string;
    rearShockAbsorberType?: string;
    fuelTank?: string;
    mudGuardFront?: string;
    frontShockAbsorber?: string;
    gearShiftLever?: string;
    mainStand?: string;
    indicators?: string;
    frontScoop?: string;
    sideCovers?: string;
    handleBar?: string;
    paintCondition?: string;
    selfStart?: string;
    mudGuardRear?: string;
    battery?: string;
    alloyOrWheelRim?: string;
    speedometerPanel?: string;
    engineFunction?: string;
    fuelGauge?: string;
    radiator?: string;
    tyre1Life?: string;
    ignition?: string;
    sideStand?: string;
    clutchCondition?: string;
}): {
    headLight: [] | [string];
    tailLamp: [] | [string];
    switches: [] | [string];
    bodyTypeScooter: [] | [string];
    silencerCover: [] | [string];
    forkBend: [] | [string];
    horn: [] | [string];
    remoteKeyWorking: [] | [string];
    keys: [] | [string];
    fuelTankCondition: [] | [string];
    engineCondition: [] | [string];
    silencer: [] | [string];
    acceleratorCondition: [] | [string];
    discBrakesRear: [] | [string];
    rearShockAbsorber: [] | [string];
    rearLHIndicator: [] | [string];
    rearRHIndicator: [] | [string];
    frontLHIndicator: [] | [string];
    frontRHIndicator: [] | [string];
    cubicCapacityCC: [] | [string];
    brakesCondition: [] | [string];
    rearBrakeLever: [] | [string];
    discBrakesFront: [] | [string];
    speedometerTachometer: [] | [string];
    tyre2Life: [] | [string];
    tailLight: [] | [string];
    rearShockAbsorberType: [] | [string];
    fuelTank: [] | [string];
    mudGuardFront: [] | [string];
    frontShockAbsorber: [] | [string];
    gearShiftLever: [] | [string];
    mainStand: [] | [string];
    indicators: [] | [string];
    frontScoop: [] | [string];
    sideCovers: [] | [string];
    handleBar: [] | [string];
    paintCondition: [] | [string];
    selfStart: [] | [string];
    mudGuardRear: [] | [string];
    battery: [] | [string];
    alloyOrWheelRim: [] | [string];
    speedometerPanel: [] | [string];
    engineFunction: [] | [string];
    fuelGauge: [] | [string];
    radiator: [] | [string];
    tyre1Life: [] | [string];
    ignition: [] | [string];
    sideStand: [] | [string];
    clutchCondition: [] | [string];
} {
    return {
        headLight: value.headLight ? candid_some(value.headLight) : candid_none(),
        tailLamp: value.tailLamp ? candid_some(value.tailLamp) : candid_none(),
        switches: value.switches ? candid_some(value.switches) : candid_none(),
        bodyTypeScooter: value.bodyTypeScooter ? candid_some(value.bodyTypeScooter) : candid_none(),
        silencerCover: value.silencerCover ? candid_some(value.silencerCover) : candid_none(),
        forkBend: value.forkBend ? candid_some(value.forkBend) : candid_none(),
        horn: value.horn ? candid_some(value.horn) : candid_none(),
        remoteKeyWorking: value.remoteKeyWorking ? candid_some(value.remoteKeyWorking) : candid_none(),
        keys: value.keys ? candid_some(value.keys) : candid_none(),
        fuelTankCondition: value.fuelTankCondition ? candid_some(value.fuelTankCondition) : candid_none(),
        engineCondition: value.engineCondition ? candid_some(value.engineCondition) : candid_none(),
        silencer: value.silencer ? candid_some(value.silencer) : candid_none(),
        acceleratorCondition: value.acceleratorCondition ? candid_some(value.acceleratorCondition) : candid_none(),
        discBrakesRear: value.discBrakesRear ? candid_some(value.discBrakesRear) : candid_none(),
        rearShockAbsorber: value.rearShockAbsorber ? candid_some(value.rearShockAbsorber) : candid_none(),
        rearLHIndicator: value.rearLHIndicator ? candid_some(value.rearLHIndicator) : candid_none(),
        rearRHIndicator: value.rearRHIndicator ? candid_some(value.rearRHIndicator) : candid_none(),
        frontLHIndicator: value.frontLHIndicator ? candid_some(value.frontLHIndicator) : candid_none(),
        frontRHIndicator: value.frontRHIndicator ? candid_some(value.frontRHIndicator) : candid_none(),
        cubicCapacityCC: value.cubicCapacityCC ? candid_some(value.cubicCapacityCC) : candid_none(),
        brakesCondition: value.brakesCondition ? candid_some(value.brakesCondition) : candid_none(),
        rearBrakeLever: value.rearBrakeLever ? candid_some(value.rearBrakeLever) : candid_none(),
        discBrakesFront: value.discBrakesFront ? candid_some(value.discBrakesFront) : candid_none(),
        speedometerTachometer: value.speedometerTachometer ? candid_some(value.speedometerTachometer) : candid_none(),
        tyre2Life: value.tyre2Life ? candid_some(value.tyre2Life) : candid_none(),
        tailLight: value.tailLight ? candid_some(value.tailLight) : candid_none(),
        rearShockAbsorberType: value.rearShockAbsorberType ? candid_some(value.rearShockAbsorberType) : candid_none(),
        fuelTank: value.fuelTank ? candid_some(value.fuelTank) : candid_none(),
        mudGuardFront: value.mudGuardFront ? candid_some(value.mudGuardFront) : candid_none(),
        frontShockAbsorber: value.frontShockAbsorber ? candid_some(value.frontShockAbsorber) : candid_none(),
        gearShiftLever: value.gearShiftLever ? candid_some(value.gearShiftLever) : candid_none(),
        mainStand: value.mainStand ? candid_some(value.mainStand) : candid_none(),
        indicators: value.indicators ? candid_some(value.indicators) : candid_none(),
        frontScoop: value.frontScoop ? candid_some(value.frontScoop) : candid_none(),
        sideCovers: value.sideCovers ? candid_some(value.sideCovers) : candid_none(),
        handleBar: value.handleBar ? candid_some(value.handleBar) : candid_none(),
        paintCondition: value.paintCondition ? candid_some(value.paintCondition) : candid_none(),
        selfStart: value.selfStart ? candid_some(value.selfStart) : candid_none(),
        mudGuardRear: value.mudGuardRear ? candid_some(value.mudGuardRear) : candid_none(),
        battery: value.battery ? candid_some(value.battery) : candid_none(),
        alloyOrWheelRim: value.alloyOrWheelRim ? candid_some(value.alloyOrWheelRim) : candid_none(),
        speedometerPanel: value.speedometerPanel ? candid_some(value.speedometerPanel) : candid_none(),
        engineFunction: value.engineFunction ? candid_some(value.engineFunction) : candid_none(),
        fuelGauge: value.fuelGauge ? candid_some(value.fuelGauge) : candid_none(),
        radiator: value.radiator ? candid_some(value.radiator) : candid_none(),
        tyre1Life: value.tyre1Life ? candid_some(value.tyre1Life) : candid_none(),
        ignition: value.ignition ? candid_some(value.ignition) : candid_none(),
        sideStand: value.sideStand ? candid_some(value.sideStand) : candid_none(),
        clutchCondition: value.clutchCondition ? candid_some(value.clutchCondition) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): {
    motorcycle: null;
} | {
    bike: null;
} | {
    scooter: null;
} {
    return value == VehicleType.motorcycle ? {
        motorcycle: null
    } : value == VehicleType.bike ? {
        bike: null
    } : value == VehicleType.scooter ? {
        scooter: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FuelType): {
    petrol: null;
} | {
    electric: null;
} {
    return value == FuelType.petrol ? {
        petrol: null
    } : value == FuelType.electric ? {
        electric: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
